spring:
  application:
    name: posdataservice
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@mongodb:27017/onlinegrocery?authSource=admin
cloud:
  loadbalancer:
    clients:
      payments:
        instances:
          - url: http://localhost:8082
metrics:
 tags:
  application: ${spring.application.name}
onlinegrocery:
 app:
  jwtSecret: ======================onlinegrocery=Spring===========================
  jwtExpirationMs: 86400000