spring:
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@mongodb:27017/onlinegrocery?authSource=admin
cloud:
  loadbalancer:
    clients:
      payments:
        instances:
          - url: http://localhost:8082
onlinegrocery:
 app:
  jwtSecret: ======================onlinegrocery=Spring===========================
  jwtExpirationMs: 86400000